### ISSUE TITLE
clarification on instructions about deployment in readme

### ISSUE THREAD

**Issue by pandeesh** [Wikia/athena_alerter#1]
Thanks for contributing tnis tool to the community. I have a clarification on the deployment process  mentioned in the readme file:
```bash
cp bin/settings.py.template bin/settings.py
vi settings.py # Or use any other editor and provide configuration
make LAMBDA_BUCKET=myorg-code-bucket LAMBDA_KEY=lambda/athena_alerter.zip CLOUDTRAIL_BUCKET=myorg-cloudtrail DYNAMODB_TABLE_NAME=athena_queries SQS_QUEUE_NAME=athena_queries run_cloudformation 
```
May I know where this is getting executed in your process? if it's from a standalone linux machine, then how the AWS account association and authorization takes place?

**Comment by MikolajBalcerek** [comment]
It's run from your development machine, you can configure your profile (for an IAM account with appropriate policies attached) using awscli `aws configure`.

You could also run it on an EC2 machine, using IAM roles.

Sorry it took so long, the original creators have moved elsewhere :)
